### ISSUE TITLE
Can't start via docker-compose: /opt/run.sh (many of them): not found. Not defined PATH?

### ISSUE THREAD

**Issue by pztrn** [Nouuu/Docker-Projeqtor#4]
Docker logs:

```
: not foundervice_1  | /opt/run.sh: 2:
projeqtor_service_1  | Init config
: not foundervice_1  | /opt/run.sh: 6:
projeqtor_service_1  | chown: cannot access '/mnt/'$'\r': No such file or directory
: not foundervice_1  | /opt/run.sh: 8:
: not foundervice_1  | /opt/run.sh: 12:
: not foundervice_1  | /opt/run.sh: 23:
projeqtor_service_1  | Init apache2
: not foundervice_1  | /opt/run.sh: 25: apache2-foreground
projeqtor_projeqtor_service_1 exited with code 127
```

Compose file:

```
version: '2.4'

services:
  mysql_service:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=projeqtor
  projeqtor_service:
    image: nospy/projeqtor:9.4.2
    depends_on:
      - mysql_service
    volumes:
      - projeqtor_documents:/mnt/documents
      - projeqtor_logs:/mnt/logs
    ports:
      - "2525:25"
      - "127.0.0.1:8989:80"
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MAX_INPUT_VARS=4000
      - PHP_MAX_UPLOAD_SIZE=1G
      - PHP_MEMORY_LIMIT=512M
      - PHP_REQUEST_TERMINATE_TIMEOUT=0
      - PJT_ATTACHMENT_MAX_SIZE_MAIL=2097152
      - PJT_DB_TYPE=mysql
      - PJT_DB_HOST=mysql_service
      - PJT_DB_PORT=3306
      - PJT_DB_NAME=projeqtor
      - PJT_DB_USER=root
      - PJT_DB_PASSWORD=changeme
volumes:
  mysql_data:
  projeqtor_documents:
  projeqtor_logs:
```

It looks like `PATH` isn't defined at all for 9.5.4 image. 9.4.2 works fine.
